apolar:
  dir: ../results/features_importance/apolar/
  all: ${feat_importance.apolar.dir}/all/
  ei_alpha: ${feat_importance.apolar.dir}/ei_alpha/
  pi_alpha: ${feat_importance.apolar.dir}/pi_alpha/
  pi_ei: ${feat_importance.apolar.dir}/pi_ei/
  
polar:
  dir: ../results/features_importance/polar/
  all: ${feat_importance.polar.dir}/all/
  alpha_dipole: ${feat_importance.polar.dir}/alpha_dipole/
  alpha_dipole_pi: ${feat_importance.polar.dir}/alpha_dipole_pi/
  ei_alpha_dipole: ${feat_importance.polar.dir}/ei_alpha_dipole/

polar_apolar:
  dir: ../results/features_importance/polar_apolar/
  all: ${feat_importance.polar_apolar.dir}/all/
  alpha_dipole: ${feat_importance.polar_apolar.dir}/alpha_dipole/
  alpha_dipole_pi: ${feat_importance.polar_apolar.dir}/alpha_dipole_pi/
  ei_alpha_dipole: ${feat_importance.polar_apolar.dir}/ei_alpha_dipole/