apolar:
  all: feature_importance/all/
  ei_alpha: feature_importance/ei_alpha/
  pi_alpha: feature_importance/pi_alpha/
  pi_ei: feature_importance/pi_ei/
  
polar:
  all: feature_importance/all/
  alpha_dipole: feature_importance/alpha_dipole/
  alpha_dipole_pi: feature_importance/alpha_dipole_pi/
  ei_alpha_dipole: feature_importance/ei_alpha_dipole/

polar_apolar:
  all: feature_importance/all/
  alpha_dipole: feature_importance/alpha_dipole/
  alpha_dipole_pi: feature_importance/alpha_dipole_pi/
  ei_alpha_dipole: feature_importance/ei_alpha_dipole/