defaults:
  - poly : space_poly
  - svr : space_svr
  - xgb : space_xgb
  - nn : space_nn
  - _self_


scaling_regressor:
  name: "regressor_scale"
  categories: [StandardScaler(),MinMaxScaler(),RobustScaler()]
  type: 'scalers'


scaling_transformer:
  name: "transformer"
  categories: [StandardScaler(),MinMaxScaler(),RobustScaler()]
  type: 'scalers'
