learning_rate:
  name: 'learning_rate'
  prior: "log-uniform"
  low: 10e-5
  high: 0.2
  type: "real"
n_estimators:
  name: 'n_estimators'
  low: 100
  high: 2000
  type: "integer"
max_depth:
  name: 'max_depth'
  low: 1
  high: 15
  type: "integer"
min_child_weight:
  name: 'min_child_weight'
  low: 1
  high: 15
  type: "integer"
gamma:
  name: "gamma"
  low: 0
  high: 6
  type: "real"
subsample:
  name: 'subsample'
  low: 0.1
  high: 1
  type: "real"
colsample_bytree:
  name: 'colsample_bytree'
  low: 0.1
  high: 1
  type: "real"
reg_alpha:
  name: 'reg_alpha'
  low: 0
  high: 1
  type: "real"
reg_lambda:
  name: 'reg_lambda'
  low: 0
  high: 1
  type: "real"




# space_xgb = [
#     Real(10e-5,0.2,  "log-uniform", name='learning_rate'),
#     Integer(100,2000,name = 'n_estimators'),
#     Integer(1,15,name='max_depth'),
#     Integer(1,15,name='min_child_weight'),
#     Real(0, 6, name='gamma'),
#     Real(0.1, 1, name='subsample'),
#     Real(0.1,1,name='colsample_bytree'),
#     Real(0,1,name="reg_alpha"),
#     Real(0,1,name="reg_lambda")
# ]
